"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});
var COUNTRIES = exports.COUNTRIES = [{
    "countryName": "Afghanistan",
    "ISOALPHA2Code": "AF",
    "ISOALPHA3Code": "AFG",
    "ISONumericalCode": 4
}, {
    "countryName": "Aland Islands",
    "ISOALPHA2Code": "AX",
    "ISOALPHA3Code": "ALA",
    "ISONumericalCode": 248
}, {
    "countryName": "Albania",
    "ISOALPHA2Code": "AL",
    "ISOALPHA3Code": "ALB",
    "ISONumericalCode": 8
}, {
    "countryName": "Algeria",
    "ISOALPHA2Code": "DZ",
    "ISOALPHA3Code": "DZA",
    "ISONumericalCode": 12
}, {
    "countryName": "American Samoa",
    "ISOALPHA2Code": "AS",
    "ISOALPHA3Code": "ASM",
    "ISONumericalCode": 16
}, {
    "countryName": "Andorra",
    "ISOALPHA2Code": "AD",
    "ISOALPHA3Code": "AND",
    "ISONumericalCode": 20
}, {
    "countryName": "Angola",
    "ISOALPHA2Code": "AO",
    "ISOALPHA3Code": "AGO",
    "ISONumericalCode": 24
}, {
    "countryName": "Anguilla",
    "ISOALPHA2Code": "AI",
    "ISOALPHA3Code": "AIA",
    "ISONumericalCode": 660
}, {
    "countryName": "Antarctica",
    "ISOALPHA2Code": "AQ",
    "ISOALPHA3Code": "ATA",
    "ISONumericalCode": 10
}, {
    "countryName": "Antigua and Barbuda",
    "ISOALPHA2Code": "AG",
    "ISOALPHA3Code": "ATG",
    "ISONumericalCode": 28
}, {
    "countryName": "Argentina",
    "ISOALPHA2Code": "AR",
    "ISOALPHA3Code": "ARG",
    "ISONumericalCode": 32
}, {
    "countryName": "Armenia",
    "ISOALPHA2Code": "AM",
    "ISOALPHA3Code": "ARM",
    "ISONumericalCode": 51
}, {
    "countryName": "Aruba",
    "ISOALPHA2Code": "AW",
    "ISOALPHA3Code": "ABW",
    "ISONumericalCode": 533
}, {
    "countryName": "Australia",
    "ISOALPHA2Code": "AU",
    "ISOALPHA3Code": "AUS",
    "ISONumericalCode": 36
}, {
    "countryName": "Austria",
    "ISOALPHA2Code": "AT",
    "ISOALPHA3Code": "AUT",
    "ISONumericalCode": 40
}, {
    "countryName": "Azerbaijan",
    "ISOALPHA2Code": "AZ",
    "ISOALPHA3Code": "AZE",
    "ISONumericalCode": 31
}, {
    "countryName": "Bahamas",
    "ISOALPHA2Code": "BS",
    "ISOALPHA3Code": "BHS",
    "ISONumericalCode": 44
}, {
    "countryName": "Bahrain",
    "ISOALPHA2Code": "BH",
    "ISOALPHA3Code": "BHR",
    "ISONumericalCode": 48
}, {
    "countryName": "Bangladesh",
    "ISOALPHA2Code": "BD",
    "ISOALPHA3Code": "BGD",
    "ISONumericalCode": 50
}, {
    "countryName": "Barbados",
    "ISOALPHA2Code": "BB",
    "ISOALPHA3Code": "BRB",
    "ISONumericalCode": 52
}, {
    "countryName": "Belarus",
    "ISOALPHA2Code": "BY",
    "ISOALPHA3Code": "BLR",
    "ISONumericalCode": 112
}, {
    "countryName": "Belgium",
    "ISOALPHA2Code": "BE",
    "ISOALPHA3Code": "BEL",
    "ISONumericalCode": 56
}, {
    "countryName": "Belize",
    "ISOALPHA2Code": "BZ",
    "ISOALPHA3Code": "BLZ",
    "ISONumericalCode": 84
}, {
    "countryName": "Benin",
    "ISOALPHA2Code": "BJ",
    "ISOALPHA3Code": "BEN",
    "ISONumericalCode": 204
}, {
    "countryName": "Bermuda",
    "ISOALPHA2Code": "BM",
    "ISOALPHA3Code": "BMU",
    "ISONumericalCode": 60
}, {
    "countryName": "Bhutan",
    "ISOALPHA2Code": "BT",
    "ISOALPHA3Code": "BTN",
    "ISONumericalCode": 64
}, {
    "countryName": "Bolivia",
    "ISOALPHA2Code": "BO",
    "ISOALPHA3Code": "BOL",
    "ISONumericalCode": 68
}, {
    "countryName": "Bosnia and Herzegovina",
    "ISOALPHA2Code": "BA",
    "ISOALPHA3Code": "BIH",
    "ISONumericalCode": 70
}, {
    "countryName": "Botswana",
    "ISOALPHA2Code": "BW",
    "ISOALPHA3Code": "BWA",
    "ISONumericalCode": 72
}, {
    "countryName": "Bouvet Island",
    "ISOALPHA2Code": "BV",
    "ISOALPHA3Code": "BVT",
    "ISONumericalCode": 74
}, {
    "countryName": "Brazil",
    "ISOALPHA2Code": "BR",
    "ISOALPHA3Code": "BRA",
    "ISONumericalCode": 76
}, {
    "countryName": "British Virgin Islands",
    "ISOALPHA2Code": "VG",
    "ISOALPHA3Code": "VGB",
    "ISONumericalCode": 92
}, {
    "countryName": "British Indian Ocean Territory",
    "ISOALPHA2Code": "IO",
    "ISOALPHA3Code": "IOT",
    "ISONumericalCode": 86
}, {
    "countryName": "Brunei Darussalam",
    "ISOALPHA2Code": "BN",
    "ISOALPHA3Code": "BRN",
    "ISONumericalCode": 96
}, {
    "countryName": "Bulgaria",
    "ISOALPHA2Code": "BG",
    "ISOALPHA3Code": "BGR",
    "ISONumericalCode": 100
}, {
    "countryName": "Burkina Faso",
    "ISOALPHA2Code": "BF",
    "ISOALPHA3Code": "BFA",
    "ISONumericalCode": 854
}, {
    "countryName": "Burundi",
    "ISOALPHA2Code": "BI",
    "ISOALPHA3Code": "BDI",
    "ISONumericalCode": 108
}, {
    "countryName": "Cambodia",
    "ISOALPHA2Code": "KH",
    "ISOALPHA3Code": "KHM",
    "ISONumericalCode": 116
}, {
    "countryName": "Cameroon",
    "ISOALPHA2Code": "CM",
    "ISOALPHA3Code": "CMR",
    "ISONumericalCode": 120
}, {
    "countryName": "Canada",
    "ISOALPHA2Code": "CA",
    "ISOALPHA3Code": "CAN",
    "ISONumericalCode": 124
}, {
    "countryName": "Cape Verde",
    "ISOALPHA2Code": "CV",
    "ISOALPHA3Code": "CPV",
    "ISONumericalCode": 132
}, {
    "countryName": "Cayman Islands",
    "ISOALPHA2Code": "KY",
    "ISOALPHA3Code": "CYM",
    "ISONumericalCode": 136
}, {
    "countryName": "Central African Republic",
    "ISOALPHA2Code": "CF",
    "ISOALPHA3Code": "CAF",
    "ISONumericalCode": 140
}, {
    "countryName": "Chad",
    "ISOALPHA2Code": "TD",
    "ISOALPHA3Code": "TCD",
    "ISONumericalCode": 148
}, {
    "countryName": "Chile",
    "ISOALPHA2Code": "CL",
    "ISOALPHA3Code": "CHL",
    "ISONumericalCode": 152
}, {
    "countryName": "China",
    "ISOALPHA2Code": "CN",
    "ISOALPHA3Code": "CHN",
    "ISONumericalCode": 156
}, {
    "countryName": "Hong Kong, SAR China",
    "ISOALPHA2Code": "HK",
    "ISOALPHA3Code": "HKG",
    "ISONumericalCode": 344
}, {
    "countryName": "Macao, SAR China",
    "ISOALPHA2Code": "MO",
    "ISOALPHA3Code": "MAC",
    "ISONumericalCode": 446
}, {
    "countryName": "Christmas Island",
    "ISOALPHA2Code": "CX",
    "ISOALPHA3Code": "CXR",
    "ISONumericalCode": 162
}, {
    "countryName": "Cocos (Keeling) Islands",
    "ISOALPHA2Code": "CC",
    "ISOALPHA3Code": "CCK",
    "ISONumericalCode": 166
}, {
    "countryName": "Colombia",
    "ISOALPHA2Code": "CO",
    "ISOALPHA3Code": "COL",
    "ISONumericalCode": 170
}, {
    "countryName": "Comoros",
    "ISOALPHA2Code": "KM",
    "ISOALPHA3Code": "COM",
    "ISONumericalCode": 174
}, {
    "countryName": "Congo (Brazzaville)",
    "ISOALPHA2Code": "CG",
    "ISOALPHA3Code": "COG",
    "ISONumericalCode": 178
}, {
    "countryName": "Congo, (Kinshasa)",
    "ISOALPHA2Code": "CD",
    "ISOALPHA3Code": "COD",
    "ISONumericalCode": 180
}, {
    "countryName": "Cook Islands",
    "ISOALPHA2Code": "CK",
    "ISOALPHA3Code": "COK",
    "ISONumericalCode": 184
}, {
    "countryName": "Costa Rica",
    "ISOALPHA2Code": "CR",
    "ISOALPHA3Code": "CRI",
    "ISONumericalCode": 188
}, {
    "countryName": "Côte d'Ivoire",
    "ISOALPHA2Code": "CI",
    "ISOALPHA3Code": "CIV",
    "ISONumericalCode": 384
}, {
    "countryName": "Croatia",
    "ISOALPHA2Code": "HR",
    "ISOALPHA3Code": "HRV",
    "ISONumericalCode": 191
}, {
    "countryName": "Cuba",
    "ISOALPHA2Code": "CU",
    "ISOALPHA3Code": "CUB",
    "ISONumericalCode": 192
}, {
    "countryName": "Cyprus",
    "ISOALPHA2Code": "CY",
    "ISOALPHA3Code": "CYP",
    "ISONumericalCode": 196
}, {
    "countryName": "Czech Republic",
    "ISOALPHA2Code": "CZ",
    "ISOALPHA3Code": "CZE",
    "ISONumericalCode": 203
}, {
    "countryName": "Denmark",
    "ISOALPHA2Code": "DK",
    "ISOALPHA3Code": "DNK",
    "ISONumericalCode": 208
}, {
    "countryName": "Djibouti",
    "ISOALPHA2Code": "DJ",
    "ISOALPHA3Code": "DJI",
    "ISONumericalCode": 262
}, {
    "countryName": "Dominica",
    "ISOALPHA2Code": "DM",
    "ISOALPHA3Code": "DMA",
    "ISONumericalCode": 212
}, {
    "countryName": "Dominican Republic",
    "ISOALPHA2Code": "DO",
    "ISOALPHA3Code": "DOM",
    "ISONumericalCode": 214
}, {
    "countryName": "Ecuador",
    "ISOALPHA2Code": "EC",
    "ISOALPHA3Code": "ECU",
    "ISONumericalCode": 218
}, {
    "countryName": "Egypt",
    "ISOALPHA2Code": "EG",
    "ISOALPHA3Code": "EGY",
    "ISONumericalCode": 818
}, {
    "countryName": "El Salvador",
    "ISOALPHA2Code": "SV",
    "ISOALPHA3Code": "SLV",
    "ISONumericalCode": 222
}, {
    "countryName": "Equatorial Guinea",
    "ISOALPHA2Code": "GQ",
    "ISOALPHA3Code": "GNQ",
    "ISONumericalCode": 226
}, {
    "countryName": "Eritrea",
    "ISOALPHA2Code": "ER",
    "ISOALPHA3Code": "ERI",
    "ISONumericalCode": 232
}, {
    "countryName": "Estonia",
    "ISOALPHA2Code": "EE",
    "ISOALPHA3Code": "EST",
    "ISONumericalCode": 233
}, {
    "countryName": "Ethiopia",
    "ISOALPHA2Code": "ET",
    "ISOALPHA3Code": "ETH",
    "ISONumericalCode": 231
}, {
    "countryName": "Falkland Islands (Malvinas)",
    "ISOALPHA2Code": "FK",
    "ISOALPHA3Code": "FLK",
    "ISONumericalCode": 238
}, {
    "countryName": "Faroe Islands",
    "ISOALPHA2Code": "FO",
    "ISOALPHA3Code": "FRO",
    "ISONumericalCode": 234
}, {
    "countryName": "Fiji",
    "ISOALPHA2Code": "FJ",
    "ISOALPHA3Code": "FJI",
    "ISONumericalCode": 242
}, {
    "countryName": "Finland",
    "ISOALPHA2Code": "FI",
    "ISOALPHA3Code": "FIN",
    "ISONumericalCode": 246
}, {
    "countryName": "France",
    "ISOALPHA2Code": "FR",
    "ISOALPHA3Code": "FRA",
    "ISONumericalCode": 250
}, {
    "countryName": "French Guiana",
    "ISOALPHA2Code": "GF",
    "ISOALPHA3Code": "GUF",
    "ISONumericalCode": 254
}, {
    "countryName": "French Polynesia",
    "ISOALPHA2Code": "PF",
    "ISOALPHA3Code": "PYF",
    "ISONumericalCode": 258
}, {
    "countryName": "French Southern Territories",
    "ISOALPHA2Code": "TF",
    "ISOALPHA3Code": "ATF",
    "ISONumericalCode": 260
}, {
    "countryName": "Gabon",
    "ISOALPHA2Code": "GA",
    "ISOALPHA3Code": "GAB",
    "ISONumericalCode": 266
}, {
    "countryName": "Gambia",
    "ISOALPHA2Code": "GM",
    "ISOALPHA3Code": "GMB",
    "ISONumericalCode": 270
}, {
    "countryName": "Georgia",
    "ISOALPHA2Code": "GE",
    "ISOALPHA3Code": "GEO",
    "ISONumericalCode": 268
}, {
    "countryName": "Germany",
    "ISOALPHA2Code": "DE",
    "ISOALPHA3Code": "DEU",
    "ISONumericalCode": 276
}, {
    "countryName": "Ghana",
    "ISOALPHA2Code": "GH",
    "ISOALPHA3Code": "GHA",
    "ISONumericalCode": 288
}, {
    "countryName": "Gibraltar",
    "ISOALPHA2Code": "GI",
    "ISOALPHA3Code": "GIB",
    "ISONumericalCode": 292
}, {
    "countryName": "Greece",
    "ISOALPHA2Code": "GR",
    "ISOALPHA3Code": "GRC",
    "ISONumericalCode": 300
}, {
    "countryName": "Greenland",
    "ISOALPHA2Code": "GL",
    "ISOALPHA3Code": "GRL",
    "ISONumericalCode": 304
}, {
    "countryName": "Grenada",
    "ISOALPHA2Code": "GD",
    "ISOALPHA3Code": "GRD",
    "ISONumericalCode": 308
}, {
    "countryName": "Guadeloupe",
    "ISOALPHA2Code": "GP",
    "ISOALPHA3Code": "GLP",
    "ISONumericalCode": 312
}, {
    "countryName": "Guam",
    "ISOALPHA2Code": "GU",
    "ISOALPHA3Code": "GUM",
    "ISONumericalCode": 316
}, {
    "countryName": "Guatemala",
    "ISOALPHA2Code": "GT",
    "ISOALPHA3Code": "GTM",
    "ISONumericalCode": 320
}, {
    "countryName": "Guernsey",
    "ISOALPHA2Code": "GG",
    "ISOALPHA3Code": "GGY",
    "ISONumericalCode": 831
}, {
    "countryName": "Guinea",
    "ISOALPHA2Code": "GN",
    "ISOALPHA3Code": "GIN",
    "ISONumericalCode": 324
}, {
    "countryName": "Guinea-Bissau",
    "ISOALPHA2Code": "GW",
    "ISOALPHA3Code": "GNB",
    "ISONumericalCode": 624
}, {
    "countryName": "Guyana",
    "ISOALPHA2Code": "GY",
    "ISOALPHA3Code": "GUY",
    "ISONumericalCode": 328
}, {
    "countryName": "Haiti",
    "ISOALPHA2Code": "HT",
    "ISOALPHA3Code": "HTI",
    "ISONumericalCode": 332
}, {
    "countryName": "Heard and Mcdonald Islands",
    "ISOALPHA2Code": "HM",
    "ISOALPHA3Code": "HMD",
    "ISONumericalCode": 334
}, {
    "countryName": "Holy See (Vatican City State)",
    "ISOALPHA2Code": "VA",
    "ISOALPHA3Code": "VAT",
    "ISONumericalCode": 336
}, {
    "countryName": "Honduras",
    "ISOALPHA2Code": "HN",
    "ISOALPHA3Code": "HND",
    "ISONumericalCode": 340
}, {
    "countryName": "Hungary",
    "ISOALPHA2Code": "HU",
    "ISOALPHA3Code": "HUN",
    "ISONumericalCode": 348
}, {
    "countryName": "Iceland",
    "ISOALPHA2Code": "IS",
    "ISOALPHA3Code": "ISL",
    "ISONumericalCode": 352
}, {
    "countryName": "India",
    "ISOALPHA2Code": "IN",
    "ISOALPHA3Code": "IND",
    "ISONumericalCode": 356
}, {
    "countryName": "Indonesia",
    "ISOALPHA2Code": "ID",
    "ISOALPHA3Code": "IDN",
    "ISONumericalCode": 360
}, {
    "countryName": "Iran, Islamic Republic of",
    "ISOALPHA2Code": "IR",
    "ISOALPHA3Code": "IRN",
    "ISONumericalCode": 364
}, {
    "countryName": "Iraq",
    "ISOALPHA2Code": "IQ",
    "ISOALPHA3Code": "IRQ",
    "ISONumericalCode": 368
}, {
    "countryName": "Ireland",
    "ISOALPHA2Code": "IE",
    "ISOALPHA3Code": "IRL",
    "ISONumericalCode": 372
}, {
    "countryName": "Isle of Man",
    "ISOALPHA2Code": "IM",
    "ISOALPHA3Code": "IMN",
    "ISONumericalCode": 833
}, {
    "countryName": "Israel",
    "ISOALPHA2Code": "IL",
    "ISOALPHA3Code": "ISR",
    "ISONumericalCode": 376
}, {
    "countryName": "Italy",
    "ISOALPHA2Code": "IT",
    "ISOALPHA3Code": "ITA",
    "ISONumericalCode": 380
}, {
    "countryName": "Jamaica",
    "ISOALPHA2Code": "JM",
    "ISOALPHA3Code": "JAM",
    "ISONumericalCode": 388
}, {
    "countryName": "Japan",
    "ISOALPHA2Code": "JP",
    "ISOALPHA3Code": "JPN",
    "ISONumericalCode": 392
}, {
    "countryName": "Jersey",
    "ISOALPHA2Code": "JE",
    "ISOALPHA3Code": "JEY",
    "ISONumericalCode": 832
}, {
    "countryName": "Jordan",
    "ISOALPHA2Code": "JO",
    "ISOALPHA3Code": "JOR",
    "ISONumericalCode": 400
}, {
    "countryName": "Kazakhstan",
    "ISOALPHA2Code": "KZ",
    "ISOALPHA3Code": "KAZ",
    "ISONumericalCode": 398
}, {
    "countryName": "Kenya",
    "ISOALPHA2Code": "KE",
    "ISOALPHA3Code": "KEN",
    "ISONumericalCode": 404
}, {
    "countryName": "Kiribati",
    "ISOALPHA2Code": "KI",
    "ISOALPHA3Code": "KIR",
    "ISONumericalCode": 296
}, {
    "countryName": "Korea (North)",
    "ISOALPHA2Code": "KP",
    "ISOALPHA3Code": "PRK",
    "ISONumericalCode": 408
}, {
    "countryName": "Korea (South)",
    "ISOALPHA2Code": "KR",
    "ISOALPHA3Code": "KOR",
    "ISONumericalCode": 410
}, {
    "countryName": "Kuwait",
    "ISOALPHA2Code": "KW",
    "ISOALPHA3Code": "KWT",
    "ISONumericalCode": 414
}, {
    "countryName": "Kyrgyzstan",
    "ISOALPHA2Code": "KG",
    "ISOALPHA3Code": "KGZ",
    "ISONumericalCode": 417
}, {
    "countryName": "Lao PDR",
    "ISOALPHA2Code": "LA",
    "ISOALPHA3Code": "LAO",
    "ISONumericalCode": 418
}, {
    "countryName": "Latvia",
    "ISOALPHA2Code": "LV",
    "ISOALPHA3Code": "LVA",
    "ISONumericalCode": 428
}, {
    "countryName": "Lebanon",
    "ISOALPHA2Code": "LB",
    "ISOALPHA3Code": "LBN",
    "ISONumericalCode": 422
}, {
    "countryName": "Lesotho",
    "ISOALPHA2Code": "LS",
    "ISOALPHA3Code": "LSO",
    "ISONumericalCode": 426
}, {
    "countryName": "Liberia",
    "ISOALPHA2Code": "LR",
    "ISOALPHA3Code": "LBR",
    "ISONumericalCode": 430
}, {
    "countryName": "Libya",
    "ISOALPHA2Code": "LY",
    "ISOALPHA3Code": "LBY",
    "ISONumericalCode": 434
}, {
    "countryName": "Liechtenstein",
    "ISOALPHA2Code": "LI",
    "ISOALPHA3Code": "LIE",
    "ISONumericalCode": 438
}, {
    "countryName": "Lithuania",
    "ISOALPHA2Code": "LT",
    "ISOALPHA3Code": "LTU",
    "ISONumericalCode": 440
}, {
    "countryName": "Luxembourg",
    "ISOALPHA2Code": "LU",
    "ISOALPHA3Code": "LUX",
    "ISONumericalCode": 442
}, {
    "countryName": "Macedonia, Republic of",
    "ISOALPHA2Code": "MK",
    "ISOALPHA3Code": "MKD",
    "ISONumericalCode": 807
}, {
    "countryName": "Madagascar",
    "ISOALPHA2Code": "MG",
    "ISOALPHA3Code": "MDG",
    "ISONumericalCode": 450
}, {
    "countryName": "Malawi",
    "ISOALPHA2Code": "MW",
    "ISOALPHA3Code": "MWI",
    "ISONumericalCode": 454
}, {
    "countryName": "Malaysia",
    "ISOALPHA2Code": "MY",
    "ISOALPHA3Code": "MYS",
    "ISONumericalCode": 458
}, {
    "countryName": "Maldives",
    "ISOALPHA2Code": "MV",
    "ISOALPHA3Code": "MDV",
    "ISONumericalCode": 462
}, {
    "countryName": "Mali",
    "ISOALPHA2Code": "ML",
    "ISOALPHA3Code": "MLI",
    "ISONumericalCode": 466
}, {
    "countryName": "Malta",
    "ISOALPHA2Code": "MT",
    "ISOALPHA3Code": "MLT",
    "ISONumericalCode": 470
}, {
    "countryName": "Marshall Islands",
    "ISOALPHA2Code": "MH",
    "ISOALPHA3Code": "MHL",
    "ISONumericalCode": 584
}, {
    "countryName": "Martinique",
    "ISOALPHA2Code": "MQ",
    "ISOALPHA3Code": "MTQ",
    "ISONumericalCode": 474
}, {
    "countryName": "Mauritania",
    "ISOALPHA2Code": "MR",
    "ISOALPHA3Code": "MRT",
    "ISONumericalCode": 478
}, {
    "countryName": "Mauritius",
    "ISOALPHA2Code": "MU",
    "ISOALPHA3Code": "MUS",
    "ISONumericalCode": 480
}, {
    "countryName": "Mayotte",
    "ISOALPHA2Code": "YT",
    "ISOALPHA3Code": "MYT",
    "ISONumericalCode": 175
}, {
    "countryName": "Mexico",
    "ISOALPHA2Code": "MX",
    "ISOALPHA3Code": "MEX",
    "ISONumericalCode": 484
}, {
    "countryName": "Micronesia, Federated States of",
    "ISOALPHA2Code": "FM",
    "ISOALPHA3Code": "FSM",
    "ISONumericalCode": 583
}, {
    "countryName": "Moldova",
    "ISOALPHA2Code": "MD",
    "ISOALPHA3Code": "MDA",
    "ISONumericalCode": 498
}, {
    "countryName": "Monaco",
    "ISOALPHA2Code": "MC",
    "ISOALPHA3Code": "MCO",
    "ISONumericalCode": 492
}, {
    "countryName": "Mongolia",
    "ISOALPHA2Code": "MN",
    "ISOALPHA3Code": "MNG",
    "ISONumericalCode": 496
}, {
    "countryName": "Montenegro",
    "ISOALPHA2Code": "ME",
    "ISOALPHA3Code": "MNE",
    "ISONumericalCode": 499
}, {
    "countryName": "Montserrat",
    "ISOALPHA2Code": "MS",
    "ISOALPHA3Code": "MSR",
    "ISONumericalCode": 500
}, {
    "countryName": "Morocco",
    "ISOALPHA2Code": "MA",
    "ISOALPHA3Code": "MAR",
    "ISONumericalCode": 504
}, {
    "countryName": "Mozambique",
    "ISOALPHA2Code": "MZ",
    "ISOALPHA3Code": "MOZ",
    "ISONumericalCode": 508
}, {
    "countryName": "Myanmar",
    "ISOALPHA2Code": "MM",
    "ISOALPHA3Code": "MMR",
    "ISONumericalCode": 104
}, {
    "countryName": "Namibia",
    "ISOALPHA2Code": "NA",
    "ISOALPHA3Code": "NAM",
    "ISONumericalCode": 516
}, {
    "countryName": "Nauru",
    "ISOALPHA2Code": "NR",
    "ISOALPHA3Code": "NRU",
    "ISONumericalCode": 520
}, {
    "countryName": "Nepal",
    "ISOALPHA2Code": "NP",
    "ISOALPHA3Code": "NPL",
    "ISONumericalCode": 524
}, {
    "countryName": "Netherlands",
    "ISOALPHA2Code": "NL",
    "ISOALPHA3Code": "NLD",
    "ISONumericalCode": 528
}, {
    "countryName": "Netherlands Antilles",
    "ISOALPHA2Code": "AN",
    "ISOALPHA3Code": "ANT",
    "ISONumericalCode": 530
}, {
    "countryName": "New Caledonia",
    "ISOALPHA2Code": "NC",
    "ISOALPHA3Code": "NCL",
    "ISONumericalCode": 540
}, {
    "countryName": "New Zealand",
    "ISOALPHA2Code": "NZ",
    "ISOALPHA3Code": "NZL",
    "ISONumericalCode": 554
}, {
    "countryName": "Nicaragua",
    "ISOALPHA2Code": "NI",
    "ISOALPHA3Code": "NIC",
    "ISONumericalCode": 558
}, {
    "countryName": "Niger",
    "ISOALPHA2Code": "NE",
    "ISOALPHA3Code": "NER",
    "ISONumericalCode": 562
}, {
    "countryName": "Nigeria",
    "ISOALPHA2Code": "NG",
    "ISOALPHA3Code": "NGA",
    "ISONumericalCode": 566
}, {
    "countryName": "Niue",
    "ISOALPHA2Code": "NU",
    "ISOALPHA3Code": "NIU",
    "ISONumericalCode": 570
}, {
    "countryName": "Norfolk Island",
    "ISOALPHA2Code": "NF",
    "ISOALPHA3Code": "NFK",
    "ISONumericalCode": 574
}, {
    "countryName": "Northern Mariana Islands",
    "ISOALPHA2Code": "MP",
    "ISOALPHA3Code": "MNP",
    "ISONumericalCode": 580
}, {
    "countryName": "Norway",
    "ISOALPHA2Code": "NO",
    "ISOALPHA3Code": "NOR",
    "ISONumericalCode": 578
}, {
    "countryName": "Oman",
    "ISOALPHA2Code": "OM",
    "ISOALPHA3Code": "OMN",
    "ISONumericalCode": 512
}, {
    "countryName": "Pakistan",
    "ISOALPHA2Code": "PK",
    "ISOALPHA3Code": "PAK",
    "ISONumericalCode": 586
}, {
    "countryName": "Palau",
    "ISOALPHA2Code": "PW",
    "ISOALPHA3Code": "PLW",
    "ISONumericalCode": 585
}, {
    "countryName": "Palestinian Territory",
    "ISOALPHA2Code": "PS",
    "ISOALPHA3Code": "PSE",
    "ISONumericalCode": 275
}, {
    "countryName": "Panama",
    "ISOALPHA2Code": "PA",
    "ISOALPHA3Code": "PAN",
    "ISONumericalCode": 591
}, {
    "countryName": "Papua New Guinea",
    "ISOALPHA2Code": "PG",
    "ISOALPHA3Code": "PNG",
    "ISONumericalCode": 598
}, {
    "countryName": "Paraguay",
    "ISOALPHA2Code": "PY",
    "ISOALPHA3Code": "PRY",
    "ISONumericalCode": 600
}, {
    "countryName": "Peru",
    "ISOALPHA2Code": "PE",
    "ISOALPHA3Code": "PER",
    "ISONumericalCode": 604
}, {
    "countryName": "Philippines",
    "ISOALPHA2Code": "PH",
    "ISOALPHA3Code": "PHL",
    "ISONumericalCode": 608
}, {
    "countryName": "Pitcairn",
    "ISOALPHA2Code": "PN",
    "ISOALPHA3Code": "PCN",
    "ISONumericalCode": 612
}, {
    "countryName": "Poland",
    "ISOALPHA2Code": "PL",
    "ISOALPHA3Code": "POL",
    "ISONumericalCode": 616
}, {
    "countryName": "Portugal",
    "ISOALPHA2Code": "PT",
    "ISOALPHA3Code": "PRT",
    "ISONumericalCode": 620
}, {
    "countryName": "Puerto Rico",
    "ISOALPHA2Code": "PR",
    "ISOALPHA3Code": "PRI",
    "ISONumericalCode": 630
}, {
    "countryName": "Qatar",
    "ISOALPHA2Code": "QA",
    "ISOALPHA3Code": "QAT",
    "ISONumericalCode": 634
}, {
    "countryName": "Réunion",
    "ISOALPHA2Code": "RE",
    "ISOALPHA3Code": "REU",
    "ISONumericalCode": 638
}, {
    "countryName": "Romania",
    "ISOALPHA2Code": "RO",
    "ISOALPHA3Code": "ROU",
    "ISONumericalCode": 642
}, {
    "countryName": "Russian Federation",
    "ISOALPHA2Code": "RU",
    "ISOALPHA3Code": "RUS",
    "ISONumericalCode": 643
}, {
    "countryName": "Rwanda",
    "ISOALPHA2Code": "RW",
    "ISOALPHA3Code": "RWA",
    "ISONumericalCode": 646
}, {
    "countryName": "Saint-Barthélemy",
    "ISOALPHA2Code": "BL",
    "ISOALPHA3Code": "BLM",
    "ISONumericalCode": 652
}, {
    "countryName": "Saint Helena",
    "ISOALPHA2Code": "SH",
    "ISOALPHA3Code": "SHN",
    "ISONumericalCode": 654
}, {
    "countryName": "Saint Kitts and Nevis",
    "ISOALPHA2Code": "KN",
    "ISOALPHA3Code": "KNA",
    "ISONumericalCode": 659
}, {
    "countryName": "Saint Lucia",
    "ISOALPHA2Code": "LC",
    "ISOALPHA3Code": "LCA",
    "ISONumericalCode": 662
}, {
    "countryName": "Saint-Martin (French part)",
    "ISOALPHA2Code": "MF",
    "ISOALPHA3Code": "MAF",
    "ISONumericalCode": 663
}, {
    "countryName": "Saint Pierre and Miquelon",
    "ISOALPHA2Code": "PM",
    "ISOALPHA3Code": "SPM",
    "ISONumericalCode": 666
}, {
    "countryName": "Saint Vincent and Grenadines",
    "ISOALPHA2Code": "VC",
    "ISOALPHA3Code": "VCT",
    "ISONumericalCode": 670
}, {
    "countryName": "Samoa",
    "ISOALPHA2Code": "WS",
    "ISOALPHA3Code": "WSM",
    "ISONumericalCode": 882
}, {
    "countryName": "San Marino",
    "ISOALPHA2Code": "SM",
    "ISOALPHA3Code": "SMR",
    "ISONumericalCode": 674
}, {
    "countryName": "Sao Tome and Principe",
    "ISOALPHA2Code": "ST",
    "ISOALPHA3Code": "STP",
    "ISONumericalCode": 678
}, {
    "countryName": "Saudi Arabia",
    "ISOALPHA2Code": "SA",
    "ISOALPHA3Code": "SAU",
    "ISONumericalCode": 682
}, {
    "countryName": "Senegal",
    "ISOALPHA2Code": "SN",
    "ISOALPHA3Code": "SEN",
    "ISONumericalCode": 686
}, {
    "countryName": "Serbia",
    "ISOALPHA2Code": "RS",
    "ISOALPHA3Code": "SRB",
    "ISONumericalCode": 688
}, {
    "countryName": "Seychelles",
    "ISOALPHA2Code": "SC",
    "ISOALPHA3Code": "SYC",
    "ISONumericalCode": 690
}, {
    "countryName": "Sierra Leone",
    "ISOALPHA2Code": "SL",
    "ISOALPHA3Code": "SLE",
    "ISONumericalCode": 694
}, {
    "countryName": "Singapore",
    "ISOALPHA2Code": "SG",
    "ISOALPHA3Code": "SGP",
    "ISONumericalCode": 702
}, {
    "countryName": "Slovakia",
    "ISOALPHA2Code": "SK",
    "ISOALPHA3Code": "SVK",
    "ISONumericalCode": 703
}, {
    "countryName": "Slovenia",
    "ISOALPHA2Code": "SI",
    "ISOALPHA3Code": "SVN",
    "ISONumericalCode": 705
}, {
    "countryName": "Solomon Islands",
    "ISOALPHA2Code": "SB",
    "ISOALPHA3Code": "SLB",
    "ISONumericalCode": 90
}, {
    "countryName": "Somalia",
    "ISOALPHA2Code": "SO",
    "ISOALPHA3Code": "SOM",
    "ISONumericalCode": 706
}, {
    "countryName": "South Africa",
    "ISOALPHA2Code": "ZA",
    "ISOALPHA3Code": "ZAF",
    "ISONumericalCode": 710
}, {
    "countryName": "South Georgia and the South Sandwich Islands",
    "ISOALPHA2Code": "GS",
    "ISOALPHA3Code": "SGS",
    "ISONumericalCode": 239
}, {
    "countryName": "South Sudan",
    "ISOALPHA2Code": "SS",
    "ISOALPHA3Code": "SSD",
    "ISONumericalCode": 728
}, {
    "countryName": "Spain",
    "ISOALPHA2Code": "ES",
    "ISOALPHA3Code": "ESP",
    "ISONumericalCode": 724
}, {
    "countryName": "Sri Lanka",
    "ISOALPHA2Code": "LK",
    "ISOALPHA3Code": "LKA",
    "ISONumericalCode": 144
}, {
    "countryName": "Sudan",
    "ISOALPHA2Code": "SD",
    "ISOALPHA3Code": "SDN",
    "ISONumericalCode": 736
}, {
    "countryName": "Suriname",
    "ISOALPHA2Code": "SR",
    "ISOALPHA3Code": "SUR",
    "ISONumericalCode": 740
}, {
    "countryName": "Svalbard and Jan Mayen Islands",
    "ISOALPHA2Code": "SJ",
    "ISOALPHA3Code": "SJM",
    "ISONumericalCode": 744
}, {
    "countryName": "Swaziland",
    "ISOALPHA2Code": "SZ",
    "ISOALPHA3Code": "SWZ",
    "ISONumericalCode": 748
}, {
    "countryName": "Sweden",
    "ISOALPHA2Code": "SE",
    "ISOALPHA3Code": "SWE",
    "ISONumericalCode": 752
}, {
    "countryName": "Switzerland",
    "ISOALPHA2Code": "CH",
    "ISOALPHA3Code": "CHE",
    "ISONumericalCode": 756
}, {
    "countryName": "Syrian Arab Republic (Syria)",
    "ISOALPHA2Code": "SY",
    "ISOALPHA3Code": "SYR",
    "ISONumericalCode": 760
}, {
    "countryName": "Taiwan, Republic of China",
    "ISOALPHA2Code": "TW",
    "ISOALPHA3Code": "TWN",
    "ISONumericalCode": 158
}, {
    "countryName": "Tajikistan",
    "ISOALPHA2Code": "TJ",
    "ISOALPHA3Code": "TJK",
    "ISONumericalCode": 762
}, {
    "countryName": "Tanzania, United Republic of",
    "ISOALPHA2Code": "TZ",
    "ISOALPHA3Code": "TZA",
    "ISONumericalCode": 834
}, {
    "countryName": "Thailand",
    "ISOALPHA2Code": "TH",
    "ISOALPHA3Code": "THA",
    "ISONumericalCode": 764
}, {
    "countryName": "Timor-Leste",
    "ISOALPHA2Code": "TL",
    "ISOALPHA3Code": "TLS",
    "ISONumericalCode": 626
}, {
    "countryName": "Togo",
    "ISOALPHA2Code": "TG",
    "ISOALPHA3Code": "TGO",
    "ISONumericalCode": 768
}, {
    "countryName": "Tokelau",
    "ISOALPHA2Code": "TK",
    "ISOALPHA3Code": "TKL",
    "ISONumericalCode": 772
}, {
    "countryName": "Tonga",
    "ISOALPHA2Code": "TO",
    "ISOALPHA3Code": "TON",
    "ISONumericalCode": 776
}, {
    "countryName": "Trinidad and Tobago",
    "ISOALPHA2Code": "TT",
    "ISOALPHA3Code": "TTO",
    "ISONumericalCode": 780
}, {
    "countryName": "Tunisia",
    "ISOALPHA2Code": "TN",
    "ISOALPHA3Code": "TUN",
    "ISONumericalCode": 788
}, {
    "countryName": "Turkey",
    "ISOALPHA2Code": "TR",
    "ISOALPHA3Code": "TUR",
    "ISONumericalCode": 792
}, {
    "countryName": "Turkmenistan",
    "ISOALPHA2Code": "TM",
    "ISOALPHA3Code": "TKM",
    "ISONumericalCode": 795
}, {
    "countryName": "Turks and Caicos Islands",
    "ISOALPHA2Code": "TC",
    "ISOALPHA3Code": "TCA",
    "ISONumericalCode": 796
}, {
    "countryName": "Tuvalu",
    "ISOALPHA2Code": "TV",
    "ISOALPHA3Code": "TUV",
    "ISONumericalCode": 798
}, {
    "countryName": "Uganda",
    "ISOALPHA2Code": "UG",
    "ISOALPHA3Code": "UGA",
    "ISONumericalCode": 800
}, {
    "countryName": "Ukraine",
    "ISOALPHA2Code": "UA",
    "ISOALPHA3Code": "UKR",
    "ISONumericalCode": 804
}, {
    "countryName": "United Arab Emirates",
    "ISOALPHA2Code": "AE",
    "ISOALPHA3Code": "ARE",
    "ISONumericalCode": 784
}, {
    "countryName": "United Kingdom",
    "ISOALPHA2Code": "GB",
    "ISOALPHA3Code": "GBR",
    "ISONumericalCode": 826
}, {
    "countryName": "United States of America",
    "ISOALPHA2Code": "US",
    "ISOALPHA3Code": "USA",
    "ISONumericalCode": 840
}, {
    "countryName": "US Minor Outlying Islands",
    "ISOALPHA2Code": "UM",
    "ISOALPHA3Code": "UMI",
    "ISONumericalCode": 581
}, {
    "countryName": "Uruguay",
    "ISOALPHA2Code": "UY",
    "ISOALPHA3Code": "URY",
    "ISONumericalCode": 858
}, {
    "countryName": "Uzbekistan",
    "ISOALPHA2Code": "UZ",
    "ISOALPHA3Code": "UZB",
    "ISONumericalCode": 860
}, {
    "countryName": "Vanuatu",
    "ISOALPHA2Code": "VU",
    "ISOALPHA3Code": "VUT",
    "ISONumericalCode": 548
}, {
    "countryName": "Venezuela (Bolivarian Republic)",
    "ISOALPHA2Code": "VE",
    "ISOALPHA3Code": "VEN",
    "ISONumericalCode": 862
}, {
    "countryName": "Viet Nam",
    "ISOALPHA2Code": "VN",
    "ISOALPHA3Code": "VNM",
    "ISONumericalCode": 704
}, {
    "countryName": "Virgin Islands, US",
    "ISOALPHA2Code": "VI",
    "ISOALPHA3Code": "VIR",
    "ISONumericalCode": 850
}, {
    "countryName": "Wallis and Futuna Islands",
    "ISOALPHA2Code": "WF",
    "ISOALPHA3Code": "WLF",
    "ISONumericalCode": 876
}, {
    "countryName": "Western Sahara",
    "ISOALPHA2Code": "EH",
    "ISOALPHA3Code": "ESH",
    "ISONumericalCode": 732
}, {
    "countryName": "Yemen",
    "ISOALPHA2Code": "YE",
    "ISOALPHA3Code": "YEM",
    "ISONumericalCode": 887
}, {
    "countryName": "Zambia",
    "ISOALPHA2Code": "ZM",
    "ISOALPHA3Code": "ZMB",
    "ISONumericalCode": 894
}, {
    "countryName": "Zimbabwe",
    "ISOALPHA2Code": "ZW",
    "ISOALPHA3Code": "ZWE",
    "ISONumericalCode": 716
}];